FROM harbor.pj.openinnolab.org.cn/pjlab/labengine-py39-pjlab:pytorch-gpu-base
USER openinnolab
COPY ./docker/common/.condarc /home/openinnolab/.condarc
RUN /usr/local/envs/ssenv/bin/python -m pip install openmim && \
    /usr/local/envs/ssenv/bin/python -m pip uninstall -y opencv-python-headless && \
    /usr/local/envs/ssenv/bin/python -m pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html && \
    /usr/local/envs/ssenv/bin/python -m pip install mmedu==0.0.7 && \
    /usr/local/envs/ssenv/bin/mim install mmcv-full==1.4.5 && \
    /usr/local/envs/ssenv/bin/mim install mmcls && \
    /usr/local/envs/ssenv/bin/mim install mmdet==2.20.0
#docker build -f docker/base/gpu_cuda_mmedu_engine/Dockerfile -t harbor.pj.openinnolab.org.cn/pjlab/labengine-py39-pjlab:mmedu-gpu-base .
